# Use an official Ruby image
FROM ruby:3.4.3-slim

# Set the working directory inside of the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . .

# Run the script
CMD ["ruby", "script.rb"]