# Use an official Python image
FROM python:3.13-slim

# Set the working directory inside of the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . .

# Run the script
CMD ["python", "main.py"]